---
# Set up OMZsh and any other prefs

- name: Get oh-my-zsh
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.zsh
    mode: 0755

- name: Check if Oh My zsh is installed
  ansible.builtin.stat:
    path: .oh-my-zsh
  register: omz_installed

- name: Install Oh My zsh
  ansible.builtin.command: /tmp/ohmyzsh_install.zsh --unattended
  when: omz_installed.stat.isdir is not defined

- name: Set Theme 'lukerandall'
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="lukerandall"
