# Gammasite non-secret vars
---
site_name: gammasite
# Traefik Setup
## DISABLED - Moving to kubernetes
deploy_traefik: false
# tls_domain_main: gammasite.garvbox.net
# tls_domain_sans: "*.gammasite.garvbox.net"
# le_prod: true
deploy_apps:
  - monitoring

# Grafana not needed in monitoring stack - runs on kube
deploy_monitoring_grafana: false

cluster_name: gammasite-prod
flux_branch: main


admin_user_name: garvin
admin_user_uid: 1666
admin_user_pass_enc: $6$pMM5fEvPfO05XkKj$RDrqKW7YSoGRM7L1ScOhdYhT16zq2IqMLANH9qnLmVwlhOAR/zhJcRIUldI7Zrel0g/IOd4p.QZ5bpODRMMgO0
