
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
light groups: !include light-groups.yaml

# Docker-friendly HTTP proxy permissions
http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 172.16.0.0/12

# Discord Notifications
notify:
  platform: discord
  name: discord
  token: !secret discord_token

# Google Home
google_assistant:
  project_id: homeassisant-gammasite
#  service_account: !include SERVICE_ACCOUNT.JSON
#  report_state: true
#  expose_by_default: false
  exposed_domains:
    - light
    - switch
    - group
  entity_config:
    switch.tasplug4:
      expose: false
    switch.tasplug3:
      expose: false
    switch.tasplug1:
      expose: false
    group.tvlights:
      room: Living Room

# Alexa Hue Emulation
emulated_hue:
  listen_port: 80
  exposed_domains:
    - light
    - switch
    - group
#  entities:
#    switch.tasplug4:
#      hidden: true
#    switch.tasplug1:
#      hidden: true

