# Portainer Docker setup - taken from install instructions cli:
# https://docs.portainer.io/v/ce-2.11/start/install/server/docker/linux
# docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.11.1
---
version: '3'
services:
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    ports:
      - 9443:9443
#      - 8000:8000
    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.homeassistant.rule=Host(`gammasite.garvbox.net`)"
#      - "traefik.http.routers.homeassistant.entrypoints=web-https"
      - "com.centurylinklabs.watchtower.enable=true"
#    networks:
#      - web
#      - ha-internal

volumes:
  portainer_data: {}

#networks:
#  web:
#    external: true

