---
# Telegraf installation handlers
- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
