---
# Install and Set up basic telegraf config

- name: Telegraf repository key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    keyring: /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg
    state: present
  become: true

- name: Telegraf repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: telegraf
  register: repo_telegraf
  become: true
  notify:
    - Update Apt Cache

- name: Install Telegraf and Sensor packages
  ansible.builtin.apt:
    name:
      - telegraf
      - lm-sensors
    state: present
  become: true
  register: install_telegraf
  notify:
    - Restart Telegraf

- name: Deploy Config file
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0644
    owner: root
    group: root
  become: true
  notify:
    - Restart Telegraf
