---
# Customised K3S Deployment for GitOps
# Disable core services as we will push them out with customisations on Flux
k3s_server:
  disable:
    - traefik
    - servicelb
    - metrics-server
# Set this as the master node
k3s_control_node: true
