# Role Defaults: docker-site
---
compose_tgt_dir: "{{ ansible_user_dir }}/docker"
docker_remove_vols: false

# Traefik Defaults
deploy_traefik: false

# App Defaults
deploy_monitoring_grafana: true

# Watchtower Defaults
deploy_watchtower: true
watchtower_no_startup_msg: true
watchtower_label_enable: true
watchtower_cleanup: true
watchtower_notification: shoutrrr
watchtower_notification_url: "{{ vault_watchtower_notification_url }}"
watchtower_schedule: "0 0 6 * * *"

# Zoneminder Defaults
zm_db_pass: zoneminder
zm_db_root_pass: zoneminder_root
zm_data_path: /data
