# Role Defaults: docker-site
---
compose_tgt_dir: "{{ ansible_user_dir }}/docker"
docker_remove_vols: false

# Traefik Defaults
deploy_traefik: false

# App Defaults
deploy_monitoring_grafana: true

# Watchtower Defaults
deploy_watchtower: true
watchtower_no_startup_msg: true
watchtower_label_enable: true
watchtower_cleanup: true
watchtower_poll_interval: 60
watchtower_notification: shoutrrr
watchtower_notification_url: ''
