# K3S Hosts file for k3s-lxd-test cluster
---
testsite:
  hosts:
    dockracken:
      ansible_host: dockracken.glenside.lan

gammasite:
  hosts:
    servapi4:
    watcher:

k3s_cluster:
  children:
    masters:
      hosts:
        k3s-test:
          ansible_host: k3s-test.glenside.lan
          k3s_server:
            disable:
              - traefik
              - servicelb
              - coredns
              - metrics-server
            data-dir: /data/k3s
    workers:
      hosts:
        # No worker hosts

docker_hosts:
  hosts:
    dockracken:
      lxd_docker_host: true
    servapi4:

unifi_controllers:
  hosts:
    watcher:

lxd_containers:
  hosts:
    dockracken:
  # vars:
  #   ansible_connection: lxd
