
- name: Check if Homeassistant data exists
  community.docker.docker_volume_info:
    name: homeassistant_ha_config
  register: ha_vol_check

- name: Check if Mosquitto data exists
  community.docker.docker_volume_info:
    name: homeassistant_mosquitto_conf
  register: mos_vol_check

- name: Deploy Homeassistant
  community.docker.docker_compose:
    project_name: homeassistant
    state: "{{ docker_tgt_state }}"
    definition:
      version: '3'
      services:
        homeassistant:
          container_name: homeassistant
          image: "ghcr.io/home-assistant/home-assistant:stable"
          volumes:
            - "ha_config:/config"
            - /etc/localtime:/etc/localtime:ro
          restart: always
          ports:
            - 8123
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.{{ tls_domain_main }}`)"
            - "traefik.http.routers.homeassistant.entrypoints=web-https"
            - "com.centurylinklabs.watchtower.enable=true"
          networks:
            - web
        mosquitto:
          container_name: mosquitto
          image: eclipse-mosquitto:2.0
          restart: always
          volumes:
            - mosquitto_conf:/mosquitto/config
          ports:
            - 1883:1883
            - 9001:9001
          networks:
            - ha-internal
          labels:
            - "com.centurylinklabs.watchtower.enable=true"
      networks:
        web:
          external: true
        ha-internal: {}
      volumes:
        ha_config: {}
        mosquitto_conf: {}
  environment:
    COMPOSE_HTTP_TIMEOUT: "600"

- name: Deploy Proxy-Resistant Initial HA config
  block:      
    - name: Copy Initial HA config
      ansible.builtin.copy:
        src: ha_init_config.yaml
        dest: /tmp/ha_init_config.yaml
        owner: garvin
        group: garvin
        mode: '0644'
    - name: Backup Running HA config from Container
      ansible.builtin.command:
        "docker cp homeassistant:/config/configuration.yaml /tmp/ha_config_backup.yaml"
      ignore_errors: true
    - name: Push initial HA config to container
      ansible.builtin.command:
        "docker cp /tmp/ha_init_config.yaml homeassistant:/config/configuration.yaml"
    - name: restart for initial config
      community.docker.docker_container:
        name: homeassistant
        state: started
        restart: true
  when: not ha_vol_check.exists

- name: Deploy Initial Mosquitto Config
  block:      
    - name: Copy Initial Mosquitto Config
      ansible.builtin.copy:
        src: mosquitto.conf
        dest: /tmp/mosquitto.conf
        owner: garvin
        group: garvin
        mode: '0644'
    - name: Backup Running Mosquitto config from Container
      ansible.builtin.command:
        "docker cp mosquitto:/mosquitto/mosquitto.conf /tmp/mosquitto.conf"
      ignore_errors: true
    - name: Push initial Mosquitto config to container
      ansible.builtin.command:
        "docker cp /tmp/mosquitto.conf mosquitto:/mosquitto/mosquitto.conf"
    - name: restart for initial config
      community.docker.docker_container:
        name: mosquitto
        state: started
        restart: true
  when: not mos_vol_check.exists
  