---
- name: Create/Check Web Network Exists
  community.docker.docker_network:
    name: web
    state: present

- name: Set LE CA
  ansible.builtin.set_fact:
    le_ca_server: "{{ '' if le_prod | default(false) else 'https://acme-staging-v02.api.letsencrypt.org/directory' }}"

- name: Setup Remote Ansible directories - infra
  ansible.builtin.file:
    path: "{{ compose_tgt_dir }}/infra"
    state: "directory"
    mode: 0755

- name: Deploy Base Infra Compose File
  ansible.builtin.template:
    src: infra.yaml.j2
    dest: "{{ compose_tgt_dir }}/infra/docker-compose.yaml"
    mode: 0644

- name: Bring up Infra Compose Project
  community.docker.docker_compose:
    project_src: "{{ compose_tgt_dir }}/infra"
    state: present
