---
- name: Install Docker Python Requirements
  ansible.builtin.pip:
    name: docker,docker-compose
    state: present
  tags:
    - client


- name: Include Site Infra Tasks
  include_tasks:
    file: infra.yml
    apply:
      tags:
        - infra
  tags:
    - infra

- name: Setup Remote Ansible directories - apps
  ansible.builtin.file:
    path: "{{ compose_tgt_dir }}/{{ item }}"
    state: "directory"
    mode: 0755
  loop: "{{ deploy_apps | default([]) }}"
  tags:
    - apps

- name: Include Site App Removal Tasks
  include_tasks:
    file: "remove/{{ item }}.yml"
    apply:
      tags:
        - apps
  loop: "{{remove_apps | default([])}}"
  tags:
    - apps

- name: Include Site App Deployment Tasks
  include_tasks:
    file: "deploy/{{ item }}.yml"
    apply:
      tags:
        - apps
  loop: "{{deploy_apps | default([])}}"
  tags:
    - apps
