

- name: Install Docker Python Requirements
  pip:
    name: docker,docker-compose
    state: present
  tags:
    - client


- name: Include Site Infra Tasks
  include_tasks:
    file: infra.yml
    apply:
      tags:
        - infra
  tags:
    - infra

- name: Include Site App Deployment Tasks
  include_tasks:
    file: "{{ item }}.yml"
    apply:
      tags:
        - apps
  loop: "{{deploy_apps | default([])}}"
  tags:
    - apps
