# Supporting App Versions and Settings for K3S Cluster Management
---
sops_version: "3.8.1"

sops_arch: "{{'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}"
sops_deb_url: "https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_{{ sops_arch }}.deb"

# Enable Root escalation
k3s_become: true

# Vault decrypted vars
flux_git_token: "{{ vault_flux_git_token }}"
sops_gpg_key: "{{ vault_sops_gpg_key }}"
