## traefik.yml
entryPoints:
  web-http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-https
          scheme: https
  web-https:
    address: ":443"
  dashboard:
    address: ":8080"

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    network: web
  file:
    filename: /ssl/certs.yml

# API and dashboard configuration
api:
  dashboard: true
  # insecure: true

# log:
#   level: DEBUG

accesslog:
  format: json
  filePath: /logs/access.log
