# Zoneminder
# Example from here:
# https://github.com/ZoneMinder/zmdockerfiles/tree/master/release/ubuntu20.04
# NOTE: Seems to be some warnings around deprecation there, support levels unclear
---
- name: Deploy Zoneminder
  community.docker.docker_container:
    name: zoneminder
    image: zoneminderhq/zoneminder:latest-ubuntu18.04
    state: started
    ports:
      - 80
    restart_policy: "unless-stopped"
    volumes:
      - zoneminder_events:/var/cache/zoneminder/events
      - zoneminder_images:/var/cache/zoneminder/images
      - zoneminder_db:/var/lib/mysql
      - zoneminder_logs:/var/log/zm
    labels:
      traefik.enable: "true"
      traefik.http.routers.zoneminder.rule: "Host(`zoneminder.{{ tls_domain_main }}`)"
      traefik.http.routers.zoneminder.entrypoints: "web-https"
      com.centurylinklabs.watchtower.enable: "true"
    env:
      TZ: "Europe/Dublin"
    networks:
      - name: "web"
    shm_size: 512m
