# testsite non-secret vars
---
lxd_server: kraken
cluster_name: alphasite-prod
flux_branch: main

# Media Server Vars
# Match Plex UID/GID for containers
media_user_uid: 6666
media_user_gid: 6666
media_tz: "Europe/Dublin"
