# K3S Auto Cluster Deplyoment
---

- name: Install K3S to all Nodes
  hosts: k3s_cluster
  vars:
    # For some reason we have to set this because the role ignores "become" at the play level
    k3s_become: true
  roles:
    - role: xanmanning.k3s
