---
- name: Get K3S Kubectl config from master node
  hosts: k3s_control[0]
  gather_facts: false

  tasks:
  - name: Create local kube directory
    ansible.builtin.file:
      path: "~/.kube"
      state: "directory"
      mode: 0755
    delegate_to: localhost

  - name: Backup current kube config
    ansible.builtin.copy:
      src: "~/.kube/config"
      dest: "/tmp/kube_config.backup"
      mode: 0644
    delegate_to: localhost
    failed_when: false

  - name: Pull Kubeconfig to local machine
    become: true
    ansible.builtin.fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: "~/.kube/config"
      flat: true

  - name: Replace target host in kubeconfig
    ansible.builtin.replace:
      path: "~/.kube/config"
      regexp: '127.0.0.1'
      replace: "{{ inventory_hostname if ansible_host == 'localhost' else ansible_host }}"
    delegate_to: localhost
