# Build a New Container and configure as a standardised host (or apply install process to existing)
# NOTE: requires lxc command and remote configured to the target LXC server

# Support for container deletion is available using "-e lxd_operation=delete", or
# using host vars

- name: Build & Configure LXD Container
  hosts: lxd_containers
  gather_facts: no

  tasks:
    - name: LXD Container Build
      ansible.builtin.import_role:
        name: lxd
        tasks_from: create

    - name: Post-Build Config tasks
      ansible.builtin.import_role:
        name: lxd
        tasks_from: post-build
