# Setup Home dir just the way I like it
---

- name: Set up Remote admin User
  hosts: all
  tasks:
    - name: Install ZSH
      ansible.builtin.apt:
        name: zsh
        state: present
      become: true

    - name: Set ZSH Shell
      ansible.builtin.user:
        shell: "/bin/zsh"
        name: "{{ ansible_user_id }}"
      become: true

    - name: Get oh-my-zsh
      ansible.builtin.get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh_install.zsh
        mode: 0755

    - name: Install Oh My zsh
      ansible.builtin.command: /tmp/ohmyzsh_install.zsh --unattended

    - name: Set Theme 'lukerandall'
      ansible.builtin.lineinfile:
        path: "~/.zshrc"
        regexp: '^ZSH_THEME='
        line: ZSH_THEME="lukerandall"
