# HomeAssistant and Mosquitto deployment
# NOTE: Configs are only pushed on initial deployment to avoid
#   potential for overwriting setups
---
- name: Create HomeAssistant Internal Network
  community.docker.docker_network:
    name: "ha-internal"
    state: present

- name: Check if Homeassistant data exists
  community.docker.docker_volume_info:
    name: homeassistant_config
  register: ha_vol_check

- name: Deploy Homeassistant
  community.docker.docker_container:
    name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    state: present
    restart_policy: "unless-stopped"
    ports:
      -  8123
    volumes:
      - "homeassistant_config:/config"
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.rule: "Host(`homeassistant.{{ tls_domain_main }}`)"
      traefik.http.routers.homeassistant.entrypoints: web-https
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - name: "web"
      - name: "ha-internal"

- name: Deploy Proxy-Resistant Initial HA config
  block:      
    - name: Copy Initial HA config
      ansible.builtin.copy:
        src: ha_init_config.yaml
        dest: /tmp/ha_init_config.yaml
    - name: Backup Running HA config from Container
      ansible.builtin.command:
        "docker cp homeassistant:/config/configuration.yaml /tmp/ha_config_backup.yaml"
      ignore_errors: true
    - name: Push initial HA config to container
      ansible.builtin.command:
        "docker cp /tmp/ha_init_config.yaml homeassistant:/config/configuration.yaml"
    - name: restart for initial config
      community.docker.docker_container:
        name: homeassistant
        state: started
        restart: true
  when: not ha_vol_check.exists

- name: Deploy Mosquitto
  community.docker.docker_container:
    name: mosquitto
    image: eclipse-mosquitto:2.0
    state: present
    restart_policy: "unless-stopped"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mosquitto_config:/mosquitto/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - name: "ha-internal"
- name: Copy Running Mosqutto Config
  ansible.builtin.command:
    "docker cp mosquitto:/mosquitto/config/mosquitto.conf /tmp/mosquitto.conf"

- name: Bind to all IPs port 1883
  ansible.builtin.lineinfile:
    path: /tmp/mosquitto.conf
    regexp: '^#?listener.*'
    line: "listener 1883"
  register: updated_mosquitto_bind

- name: Allow Anonymous Connections
  ansible.builtin.lineinfile:
    path: /tmp/mosquitto.conf
    regexp: '^#?allow_anonymous.*'
    line: "allow_anonymous true"
  register: updated_mosquitto_anon
- name: Push Updated Mosquitto config to container
  ansible.builtin.command:
    "docker cp /tmp/mosquitto.conf mosquitto:/mosquitto/config/mosquitto.conf"
  when: updated_mosquitto_bind.changed or updated_mosquitto_anon.changed

- name: restart for initial config
  community.docker.docker_container:
    name: mosquitto
    state: started
    restart: true
  when: updated_mosquitto_bind.changed or updated_mosquitto_anon.changed
