# HomeAssistant and Mosquitto deployment
# NOTE: Configs are only pushed on initial deployment to avoid
#   potential for overwriting setups
---
- name: Check if Homeassistant data exists
  community.docker.docker_volume_info:
    name: homeassistant_ha-config
  register: ha_vol_check

- name: Deploy Homeassistant Compose File
  ansible.builtin.template:
    src: homeassistant.yaml.j2
    dest: "{{ compose_tgt_dir }}/homeassistant/docker-compose.yaml"
    mode: 0644

- name: Bring up Homeassistant Compose Project
  community.docker.docker_compose:
    project_src: "{{ compose_tgt_dir }}/homeassistant"
    state: present

- name: Deploy Proxy-Resistant Initial HA config
  block:
    - name: Copy Initial HA config
      ansible.builtin.copy:
        src: ha_init_config.yaml
        dest: /tmp/ha_init_config.yaml
        mode: '0664'
    - name: Backup Running HA config from Container
      ansible.builtin.command:
        "docker cp homeassistant_homeassistant_1:/config/configuration.yaml /tmp/ha_config_backup.yaml"
      failed_when: false
    - name: Push initial HA config to container
      ansible.builtin.command:
        "docker cp /tmp/ha_init_config.yaml homeassistant_homeassistant_1:/config/configuration.yaml"
    - name: restart for initial config
      community.docker.docker_container:
        name: homeassistant_homeassistant_1
        state: started
        restart: true
  when: not ha_vol_check.exists

- name: Copy Running Mosqutto Config
  ansible.builtin.command:
    "docker cp homeassistant_mosquitto_1:/mosquitto/config/mosquitto.conf /tmp/mosquitto.conf"

- name: Bind to all IPs port 1883
  ansible.builtin.lineinfile:
    path: /tmp/mosquitto.conf
    regexp: '^#?listener.*'
    line: "listener 1883"
  register: updated_mosquitto_bind
  notify:
    - Push Mosquitto config
    - Restart Mosquitto

- name: Allow Anonymous Connections
  ansible.builtin.lineinfile:
    path: /tmp/mosquitto.conf
    regexp: '^#?allow_anonymous.*'
    line: "allow_anonymous true"
  register: updated_mosquitto_anon
  notify:
    - Push Mosquitto config
    - Restart Mosquitto
