# InfluxDB Monitoring Services deployment
# NOTE: Configs are only pushed on initial deployment to avoid
#   potential for overwriting setups
---

- name: Deploy Monitoring Compose File
  ansible.builtin.template:
    src: monitoring.yaml.j2
    dest: "{{ compose_tgt_dir }}/monitoring/docker-compose.yaml"
    mode: 0644

- name: Bring up monitoring Compose Project
  community.docker.docker_compose:
    project_src: "{{ compose_tgt_dir }}/monitoring"
    state: present
